### ISSUE TITLE
Support latest NNBD package:args

### ISSUE THREAD

**Issue by grouma** [kevmoo/completion.dart#16]
Looks like we don't support the latest NNBD `package:args` version as we depend on this now hidden type [OptionType](https://github.com/kevmoo/completion.dart/blob/1bd94670deeab0386a34b37736d0100548d36b30/lib/src/get_args_completions.dart#L261).

**Comment by natebosch** [comment]
Will be closed by https://github.com/dart-lang/args/pull/175
